version: 2.1
jobs: 
  build:
    working_directory: /tmp/workspace
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    steps:
      - checkout

      - restore_cache: 
          key: v1-repo-{{ checksum "pom.xml" }}
      
      - run:
          name: build start
          command: echo "build start"

      - run:
          name: build project
          command: mvn clean install -D maven.test.skip=true
      - run:
          name: bulid success
          command: echo "build success"
          when: on_success
      - run:
          name: build fail
          command: echo "build failur"
          when: on_fail
      - persist_to_workspace:
          root: .
          paths:
          - ./*
  deploy:
    machine:
      timezone:
      enabled: true
    working_directory: /tmp/workspace
    steps:
      - run: echo "====================部署开始=============================="
      - attach_workspace:
          at: /tmp/workspace
      - run: ls -la && pwd && chmod 777 ./.circleci/deploy-master.sh
      - run:
          name: Deploy Over SSH
          command: ./.circleci/deploy-master.sh
      - run: echo "====================部署完毕=============================="
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master